# Generated by Django 2.0 on 2017-12-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171226_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
