# Generated by Django 2.0 on 2017-12-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userId',
            field=models.CharField(max_length=30),
        ),
    ]
