# Generated by Django 2.0 on 2017-12-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171226_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='discriminator',
            field=models.CharField(max_length=4),
        ),
    ]
