# Generated by Django 2.0 on 2017-12-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171226_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='guilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildId', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=100)),
                ('settings', models.CharField(max_length=500)),
            ],
        ),
    ]
